package image

import (
	"fmt"
	"image"
	"image/color"
	"sort"
)

// PrototypeDirectionPaletteOptions controls the shared colour pass applied to
// all direction views of one prototype. Direction views are generated by the
// model in one request, but their per-frame reductions otherwise keep slightly
// different representatives for the same material or body region.
type PrototypeDirectionPaletteOptions struct {
	PaletteSize           int  `json:"palette_size"`
	AdaptiveSparsePalette bool `json:"adaptive_sparse_palette"`
}

// directionColourMergeDistance is deliberately much smaller than the accent
// threshold used by the regular pixel pass. The direction pass is only for
// collapsing near-duplicate representatives (for example two slightly
// different reds selected for the same blade), not for recolouring a whole
// frame through a second aggressive median-cut palette.
const directionColourMergeDistance = 0.006

type directionColourStat struct {
	colour color.NRGBA
	weight uint64
}

type directionColourCanonical struct {
	colour color.NRGBA
	lab    oklabColour
}

// HarmonizePrototypeDirectionColours makes near-equivalent colours stable
// across all direction frames of one prototype. It intentionally does not run
// another global palette reduction: that would allow a dominant direction to
// erase a small but meaningful line, gem, eye, or blade highlight in another
// direction.
//
// The pass only maps a source colour to an existing source colour from the
// complete direction set when the perceptual distance is below the strict
// merge threshold. It never moves pixels, changes geometry, creates RGB
// colours, or changes alpha.
func HarmonizePrototypeDirectionColours(
	inputs []image.Image,
	options PrototypeDirectionPaletteOptions,
) ([]*image.RGBA, error) {
	if len(inputs) == 0 {
		return nil, nil
	}

	frames := make([]*image.NRGBA, len(inputs))
	for index, input := range inputs {
		if input == nil {
			return nil, fmt.Errorf("prototype direction %d image is nil", index)
		}
		frame := toNRGBA(input)
		if frame.Bounds().Empty() {
			return nil, fmt.Errorf("prototype direction %d image is empty", index)
		}
		frames[index] = frame
	}

	// A zero palette size means that the caller explicitly requested source
	// colours to be preserved. This also keeps the helper safe for callers that
	// reuse it outside the prototype pixel pipeline.
	if options.PaletteSize > 0 {
		canonical := buildDirectionColourCanonicalization(frames)
		for _, frame := range frames {
			applyDirectionColourCanonicalization(frame, canonical)
			scrubTransparentNRGBA(frame)
		}
	}

	outputs := make([]*image.RGBA, len(frames))
	for index, frame := range frames {
		outputs[index] = ToRGBA(frame)
	}
	return outputs, nil
}

func buildDirectionColourCanonicalization(frames []*image.NRGBA) map[pixelColourKey]color.NRGBA {
	stats := make(map[pixelColourKey]directionColourStat)
	for _, frame := range frames {
		for y := frame.Bounds().Min.Y; y < frame.Bounds().Max.Y; y++ {
			for x := frame.Bounds().Min.X; x < frame.Bounds().Max.X; x++ {
				pixel := frame.NRGBAAt(x, y)
				if pixel.A <= TransparentAlphaMax {
					continue
				}
				key := colourKey(pixel)
				stat := stats[key]
				stat.colour = color.NRGBA{R: pixel.R, G: pixel.G, B: pixel.B, A: 255}
				stat.weight += uint64(pixel.A)
				stats[key] = stat
			}
		}
	}

	ordered := make([]directionColourStat, 0, len(stats))
	for _, stat := range stats {
		ordered = append(ordered, stat)
	}
	sort.Slice(ordered, func(left, right int) bool {
		leftKey := colourKey(ordered[left].colour)
		rightKey := colourKey(ordered[right].colour)
		if ordered[left].weight != ordered[right].weight {
			return ordered[left].weight > ordered[right].weight
		}
		return leftKey < rightKey
	})

	canonical := make([]directionColourCanonical, 0, len(ordered))
	mapping := make(map[pixelColourKey]color.NRGBA, len(ordered))
	for _, stat := range ordered {
		candidate := directionColourCanonical{
			colour: stat.colour,
			lab:    nrgbaToOKLab(stat.colour),
		}
		mapped := stat.colour
		for _, existing := range canonical {
			if perceptualColourDistance(candidate.lab, existing.lab) <= directionColourMergeDistance {
				mapped = existing.colour
				break
			}
		}
		if colourKey(mapped) == colourKey(stat.colour) {
			canonical = append(canonical, candidate)
		}
		mapping[colourKey(stat.colour)] = mapped
	}
	return mapping
}

func applyDirectionColourCanonicalization(
	frame *image.NRGBA,
	mapping map[pixelColourKey]color.NRGBA,
) {
	for y := frame.Bounds().Min.Y; y < frame.Bounds().Max.Y; y++ {
		for x := frame.Bounds().Min.X; x < frame.Bounds().Max.X; x++ {
			pixel := frame.NRGBAAt(x, y)
			if pixel.A <= TransparentAlphaMax {
				continue
			}
			mapped, ok := mapping[colourKey(pixel)]
			if !ok {
				continue
			}
			mapped.A = pixel.A
			frame.SetNRGBA(x, y, mapped)
		}
	}
}
