coverage:
  status:
    project:
      frontend:
        flags:
          - frontend
        target: auto
        threshold: 0%
        informational: true
      backend:
        flags:
          - backend
        target: auto
        threshold: 0%
        informational: true
